xpp: if $dahdi_hardware is empty, don't use it in an error message
git-svn-id: http://svn.asterisk.org/svn/dahdi/tools/trunk@6668 a0bf4364-ded3-4de4-8d8a-66a801d63aff

diff --git a/xpp/waitfor_xpds b/xpp/waitfor_xpds
--- a/xpp/waitfor_xpds
+++ b/xpp/waitfor_xpds
@@ -37,7 +37,7 @@ ab_list() {
 
 # Any hardware?
 if ! dahdi_hardware="`which dahdi_hardware 2>/dev/null`"; then
-	echo >&2 "$0: Missing $dahdi_hardware"
+	echo >&2 "$0: Missing dahdi_hardware"
 	exit 0
 fi
 if [ "`$dahdi_hardware | grep xpp_usb`" = "" ]; then
